# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"5\n\x0fUserCredentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"&\n\tTokenInfo\x12\x0b\n\x03sub\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"&\n\x13TokenRevokeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa3\x01\n\x0b\x41uthService\x12\x34\n\x10\x41uthenticateUser\x12\x10.UserCredentials\x1a\x0e.TokenResponse\x12*\n\rValidateToken\x12\r.TokenRequest\x1a\n.TokenInfo\x12\x32\n\x0bRevokeToken\x12\r.TokenRequest\x1a\x14.TokenRevokeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERCREDENTIALS']._serialized_start=14
  _globals['_USERCREDENTIALS']._serialized_end=67
  _globals['_TOKENRESPONSE']._serialized_start=69
  _globals['_TOKENRESPONSE']._serialized_end=99
  _globals['_TOKENREQUEST']._serialized_start=101
  _globals['_TOKENREQUEST']._serialized_end=130
  _globals['_TOKENINFO']._serialized_start=132
  _globals['_TOKENINFO']._serialized_end=170
  _globals['_TOKENREVOKERESPONSE']._serialized_start=172
  _globals['_TOKENREVOKERESPONSE']._serialized_end=210
  _globals['_AUTHSERVICE']._serialized_start=213
  _globals['_AUTHSERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
